version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  user-service:
    build: ./user-service
    ports:
      - "4001:4001"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo-user:27017/userdb
    

  product-service:
    build: ./product-service
    ports:
      - "4002:4002"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo-product:27017/productdb
  
  order-service:
    build: ./order-service
    ports:
      - "4003:4003"
    depends_on:
      - user-service
      - product-service
      - mongo
    environment:
      - MONGO_URL=mongodb://mongodb:27017/orders

volumes:
  mongo-data: